from frontend import validate_args
from translator import call_translator
from utilities import bit_string,unix_time
from re2smt.re2smt import re2smt
from z3 import Solver, sat
import argparse as ap
import json
import csv
import os
import tempfile
import shutil
import time
from pathlib import Path
import copy

req_num = None

ops = {
    'StringEquals': "string",
    'StringNotEquals': "string",
    'StringNotEqualsIfExists': "string",
    'StringEqualsIgnoreCase': "string",
    'StringNotEqualsIgnoreCase': "string",
    'StringLike': "string",
    'StringNotLike': "string",
    'NumericEquals': "numeric",
    'NumericNotEquals': "numeric",
    'NumericLessThan': "numeric",
    'NumericLessThanEquals': "numeric",
    'NumericGreaterThan': "numeric",
    'NumericGreaterThanEquals': "numeric",
    'DateEquals': "date",
    'DateNotEquals': "date",
    'ForAllValues:StringEquals': "string",
    'DateLessThan': "date",
    'DateLessThanEquals': "date",
    'DateGreaterThan': "date",
    'DateGreaterThanEquals': "date",
    'Bool': "bool",
    'BinaryEquals': "string",
    'IpAddress': "ip",
    'NotIpAddress': "ip",
    'ArnEquals': "string",
    'ArnNotEquals': "string",
    'ArnLike': "string",
    'ArnNotLike': "string",
    'Null': "null"
}


solver_call_count = 0

def increment_solver_calls():
    global solver_call_count
    solver_call_count += 1
    return solver_call_count

def get_solver_calls():
    global solver_call_count
    return solver_call_count

def reset_solver_calls():
    global solver_call_count
    solver_call_count = 0

def extract_policy_statements(policy_file):
    """Extract individual statements from a policy file"""
    with open(policy_file, 'r') as f:
        policy_data = json.load(f)
    
    statements = []
    if 'Statement' in policy_data:
        statements = policy_data['Statement']
    elif isinstance(policy_data, list):
        statements = policy_data
    
    return policy_data, statements

def create_temporary_policy(statement, original_policy_structure):
    """Create a temporary policy file with just one statement"""
    temp_policy = original_policy_structure.copy()
    temp_policy['Statement'] = [statement]
    
    # Create temporary file
    temp_file = tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False)
    json.dump(temp_policy, temp_file, indent=2)
    temp_file.close()
    
    return temp_file.name

def create_universal_allow_policy():
    """Create a universal policy that allows everything"""
    universal_policy = {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "AllowEverything",
                "Effect": "Allow",
                "Action": "*",
                "Resource": "*",
                "Principal": "*"
            }
        ]
    }
    
    temp_file = tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False)
    json.dump(universal_policy, temp_file, indent=2)
    temp_file.close()
    
    return temp_file.name

def create_policy_with_statements(statements, original_policy_structure):
    """Create a temporary policy file with multiple statements"""
    temp_policy = copy.deepcopy(original_policy_structure)
    temp_policy['Statement'] = statements
    
    # Create temporary file
    temp_file = tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False)
    json.dump(temp_policy, temp_file, indent=2)
    temp_file.close()
    
    return temp_file.name

def test_request_against_policy(request_data, policy_file, args):
    """Test a single request against a policy and return the result"""
    
    # Create temporary args for this test
    temp_args = ap.Namespace(**vars(args))
    temp_args.policy1 = policy_file
    temp_args.policy2 = None
    temp_args.output = f"{args.output}_fault_test_{int(time.time())}"
    
    try:
        # Run the SMT translation
        call_translator(temp_args)
        
        # Load the SMT file generated by call_translator
        smt_file = f"{temp_args.output}_1.smt2"
        base_smt = []
        with open(smt_file) as f:
            for line in f:
                if line.strip() not in ("(check-sat)", "(get-model)"):
                    base_smt.append(line)
        base_smt = ''.join(base_smt)

        # Extract request components
        action = request_data['action']
        resource = request_data['resource']
        principal = request_data['principal']
        condition = request_data['condition']

        solver = Solver()
        smt_parts = [base_smt]

        # Assert action & resource
        a = action.lower()
        r = resource
        smt_parts.append(f'(assert (= action "{a}"))\n')
        smt_parts.append(f'(assert (= resource "{r}"))\n')

        if principal and principal != 'None':
            smt_parts.append(f'(assert (= principal "{principal}"))\n')

        # Assert conditions
        if condition and condition != 'None':
            condition_dict = eval(condition) if isinstance(condition, str) and condition != 'None' else condition
            if condition_dict:
                for key, val in condition_dict.items():
                    k = key.replace(':', '.')
                    vals = val if isinstance(val, list) else [val]
                    clauses = []
                    for v in vals:
                        if isinstance(v, int):
                            clauses.append(f"(= {k} {v})")
                        elif isinstance(v, str) and "Ip" not in key:
                            ev = v
                            clauses.append(f'(= {k} "{ev}")')
                        elif isinstance(v, str):
                            addr, pref = bit_string(v)
                            re_expr = re2smt(addr[:pref])
                            clauses.append(f"(str.in.re {k} {re_expr})")
                    if clauses:
                        if len(clauses) > 1:
                            smt_parts.append(f"(assert (or {' '.join(clauses)}))\n")
                        else:
                            smt_parts.append(f"(assert {clauses[0]})\n")

        smt_parts.append("(check-sat)")
        full_smt = ''.join(smt_parts).replace('\x00', '\x01')

        # Solve
        solver.from_string(full_smt)
        increment_solver_calls()
        solver_result = solver.check()
        
        # Determine actual result
        actual_result = 'allow' if solver_result == sat else 'deny'
        
        return actual_result
        
    except Exception as e:
        print(f"Error testing request against policy: {e}")
        return 'error'
        
    finally:
        # Clean up temporary files
        smt_file = f"{temp_args.output}_1.smt2"
        if os.path.exists(smt_file):
            os.unlink(smt_file)
def perform_fault_localization(all_results, original_policy_structure, statements, args):
    """
    Perform fault localization according to the specified algorithm:
    
    Case 1: request(rm) is allowed but should be denied
    Case 2a: rm is denied but should be allowed (explicitly denied)
    Case 2b: rm is denied but should be allowed (implicitly denied)
    """
    print("\n" + "="*80)
    print("PERFORMING FAULT LOCALIZATION")
    print("="*80)
    
    fault_localization_results = []
    
    # Get all misclassified requests
    misclassified_requests = [r for r in all_results if not r['is_correct']]
    
    print(f"Found {len(misclassified_requests)} misclassified requests to analyze")
    
    # Separate allow and deny statements from policy P
    s_allow = [s for s in statements if s.get('Effect', '').lower() == 'allow']
    s_deny = [s for s in statements if s.get('Effect', '').lower() == 'deny']
    
    print(f"Policy P has {len(s_allow)} Allow statements and {len(s_deny)} Deny statements")
    
    for req in misclassified_requests:
        print(f"\nAnalyzing misclassified request: {req['individual_request_id']}")
        print(f"  Expected: {req['expected_effect']}, Got: {req['actual_result']}")
        
        request_data = {
            'action': req['action'],
            'resource': req['resource'],
            'principal': req['principal'],
            'condition': req['condition']
        }
        
        responsible_statements = []
        fault_type = ""
        
        if req['expected_effect'] == 'deny' and req['actual_result'] == 'allow':
            # CASE 1: Request should be denied but is allowed
            print(f"  CASE 1: Request should be denied but is explicitly allowed")
            fault_type = "should_be_denied_but_explicitly_allowed"
            
            s_allow_of_rm = []
            
            # For si in S_allow, create Pi with si only
            for stmt in s_allow:
                stmt_id = stmt.get('Sid', stmt.get('sid', 'UnknownStmt'))
                print(f"    Testing Allow statement: {stmt_id}")
                
                # Create Pi = {si} (policy containing only this allow statement)
                pi_file = create_temporary_policy(stmt, original_policy_structure)
                
                try:
                    result = test_request_against_policy(request_data, pi_file, args)
                    print(f"      Result with Pi containing only {stmt_id}: {result}")
                    
                    # If rm is allowed by Pi, add si to s_allow_of_rm
                    if result == 'allow':
                        s_allow_of_rm.append(stmt_id)
                        responsible_statements.append({
                            'statement_id': stmt_id,
                            'statement': stmt,
                            'effect': 'Allow'
                        })
                        print(f" Statement {stmt_id} allows this request")
                    
                finally:
                    if os.path.exists(pi_file):
                        os.unlink(pi_file)
            
            print(f"  s_allow_of_rm = {s_allow_of_rm}")
            
        elif req['expected_effect'] == 'allow' and req['actual_result'] == 'deny':
            # CASE 2: Request should be allowed but is denied
            print(f"  CASE 2: Request should be allowed but is denied")
            
            # Create universal policy P' that allows everything
            p_prime_stmt = {
                "Sid": "AllowEverything",
                "Effect": "Allow", 
                "Action": "*",
                "Resource": "*"
            }
            
            s_deny_of_rm = []
            
            # For si in s_deny: create Pii = P' ∪ si
            for stmt in s_deny:
                stmt_id = stmt.get('Sid', stmt.get('sid', 'UnknownStmt'))
                print(f"    Testing Deny statement: {stmt_id}")
                
                # Create Pii = P' ∪ si (universal allow + this deny statement)
                pii_statements = [p_prime_stmt, stmt]
                pii_file = create_policy_with_statements(pii_statements, original_policy_structure)
                
                try:
                    result = test_request_against_policy(request_data, pii_file, args)
                    print(f"      Result with Pii (universal_allow + {stmt_id}): {result}")
                    
                    # If rm is denied by Pii, add si to s_deny_of_rm
                    if result == 'deny':
                        s_deny_of_rm.append(stmt_id)
                        responsible_statements.append({
                            'statement_id': stmt_id,
                            'statement': stmt,
                            'effect': 'Deny'
                        })
                        print(f" Statement {stmt_id} denies this request")
                    
                finally:
                    if os.path.exists(pii_file):
                        os.unlink(pii_file)
            
            # Determine sub-case based on s_deny_of_rm
            if s_deny_of_rm:
                # CASE 2a: Explicitly denied by statement(s)
                fault_type = "should_be_allowed_but_explicitly_denied"
                print(f"  CASE 2a: Explicitly denied by statements: {s_deny_of_rm}")
            else:
                # CASE 2b: Implicitly denied (no explicit deny statements affect it)
                fault_type = "should_be_allowed_but_implicitly_denied"
                print(f"  CASE 2b: Implicitly denied (no explicit deny statement affects request)")
                # responsible_statements remains empty for implicit denial
        
        # Store the fault localization result
        fault_result = {
            'request_id': req['individual_request_id'],
            'request_object_id': req['request_object_id'],
            'action': req['action'],
            'resource': req['resource'],
            'principal': req['principal'],
            'condition': req['condition'],
            'expected_effect': req['expected_effect'],
            'actual_result': req['actual_result'],
            'fault_type': fault_type,
            'responsible_statements': responsible_statements,
            'responsible_statement_ids': [s['statement_id'] for s in responsible_statements]
        }
        
        fault_localization_results.append(fault_result)
        
        print(f"  Final analysis:")
        print(f"    Fault type: {fault_type}")
        print(f"    Responsible statements: {[s['statement_id'] for s in responsible_statements]}")
    
    return fault_localization_results


def save_fault_localization_results(fault_results, args, policy_name=None, policy_index=None):
    """Save fault localization results in easily parseable format for LLM"""
    
    policy_info = f"Policy {policy_index}" if policy_index is not None else f"Policy {policy_name}" if policy_name else "Policy"
    
    home_dir = Path(args.output_dir)
    home_dir.mkdir(parents=True, exist_ok=True)

    if args.output and os.path.isabs(args.output):
        base_filename = os.path.basename(args.output)
    else:
        base_filename = args.output if args.output else "policy_validation"

    # Group results by fault type for clear categorization
    fault_groups = {
        "should_be_denied_but_explicitly_allowed": [],
        "should_be_allowed_but_explicitly_denied": [], 
        "should_be_allowed_but_implicitly_denied": []
    }
    
    for result in fault_results:
        fault_type = result['fault_type']
        if fault_type in fault_groups:
            fault_groups[fault_type].append(result)
    
    llm_report_path = home_dir / f"{base_filename}_llm_report.txt"
    with open(llm_report_path, 'w', encoding='utf-8') as f:
        f.write("POLICY FAULT LOCALIZATION REPORT\n")
        f.write("="*50 + "\n\n")
        
        f.write(f"Policy: {policy_name}\n")
        if policy_index is not None:
            f.write(f"Policy Index: {policy_index}\n")
        f.write(f"Total Misclassified Requests: {len(fault_results)}\n\n")
        
        # Category 1: Should be denied but explicitly allowed
        if fault_groups["should_be_denied_but_explicitly_allowed"]:
            f.write("SHOULD BE DENIED BUT EXPLICITLY ALLOWED\n")
            f.write("-" * 50 + "\n")
            f.write("These requests should be DENIED but are ALLOWED by the following statements:\n\n")
            
            for result in fault_groups["should_be_denied_but_explicitly_allowed"]:
                f.write(f"Request: {result['request_id']}\n")
                f.write(f"  Action: {result['action']}\n")
                f.write(f"  Resource: {result['resource']}\n")
                f.write(f"  Principal: {result['principal']}\n")
                f.write(f"  Condition: {result['condition']}\n")
                f.write(f"  Expected: {result['expected_effect']}, Got: {result['actual_result']}\n")
                f.write(f"  Responsible Statements: {', '.join(result['responsible_statement_ids'])}\n\n")
        
        # Category 2: Should be allowed but explicitly denied
        if fault_groups["should_be_allowed_but_explicitly_denied"]:
            f.write("SHOULD BE ALLOWED BUT EXPLICITLY DENIED\n")
            f.write("-" * 50 + "\n")
            f.write("These requests should be ALLOWED but are DENIED by the following statements:\n\n")
            
            for result in fault_groups["should_be_allowed_but_explicitly_denied"]:
                f.write(f"Request: {result['request_id']}\n")
                f.write(f"  Action: {result['action']}\n")
                f.write(f"  Resource: {result['resource']}\n")
                f.write(f"  Principal: {result['principal']}\n")
                f.write(f"  Condition: {result['condition']}\n")
                f.write(f"  Expected: {result['expected_effect']}, Got: {result['actual_result']}\n")
                f.write(f"  Responsible Statements: {', '.join(result['responsible_statement_ids'])}\n\n")
        
        # Category 3: Should be allowed but implicitly denied
        if fault_groups["should_be_allowed_but_implicitly_denied"]:
            f.write("SHOULD BE ALLOWED BUT IMPLICITLY DENIED\n")
            f.write("-" * 50 + "\n")
            f.write("These requests should be ALLOWED but are IMPLICITLY DENIED (no explicit allow statement):\n\n")
            
            for result in fault_groups["should_be_allowed_but_implicitly_denied"]:
                f.write(f"Request: {result['request_id']}\n")
                f.write(f"  Action: {result['action']}\n")
                f.write(f"  Resource: {result['resource']}\n")
                f.write(f"  Principal: {result['principal']}\n")
                f.write(f"  Condition: {result['condition']}\n")
                f.write(f"  Expected: {result['expected_effect']}, Got: {result['actual_result']}\n")
                f.write(f"  Responsible Statements: None (missing allow statement)\n\n")
    
    # Save detailed CSV for programmatic access
    fault_csv_path = home_dir / f"{base_filename}_fault_localization.csv"
    with open(fault_csv_path, 'w', newline='', encoding='utf-8') as csvfile:
        fieldnames = ['request_id', 'request_object_id', 'action', 'resource', 'principal', 'condition',
                     'expected_effect', 'actual_result', 'fault_type', 'responsible_statement_ids']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        
        writer.writeheader()
        for result in fault_results:
            writer.writerow({
                'request_id': result['request_id'],
                'request_object_id': result['request_object_id'],
                'action': result['action'],
                'resource': result['resource'],
                'principal': result['principal'],
                'condition': result['condition'],
                'expected_effect': result['expected_effect'],
                'actual_result': result['actual_result'],
                'fault_type': result['fault_type'],
                'responsible_statement_ids': ', '.join(result['responsible_statement_ids'])
            })
    
    print(f"\n{policy_info}: Fault localization reports saved to:")
    print(f"  LLM-friendly report: {llm_report_path}")
    print(f"  Detailed CSV: {fault_csv_path}")
    
    return llm_report_path, fault_csv_path


def test_single_statement(statement, original_policy_structure, args, policy_name=None, policy_index=None):
    """Test a single statement by creating a temporary policy and running validation"""
    
    # Create temporary policy with just this statement
    temp_policy_file = create_temporary_policy(statement, original_policy_structure)
    
    # Initialize temp_args outside try block
    temp_args = None
    
    try:
        # Create temporary args for this statement
        temp_args = ap.Namespace(**vars(args))
        temp_args.policy1 = temp_policy_file
        temp_args.policy2 = None
        
        # Generate a unique output name for this statement
        stmt_id = statement.get('Sid', statement.get('sid', 'UnknownStmt'))
        temp_args.output = f"{args.output}_temp_{stmt_id}"
        
        # Run the SMT translation and validation
        call_translator(temp_args)
        statement_results = validate_requests_for_statement(temp_args, policy_name, policy_index)
        
        # Determine if this statement has any failures
        total_requests = len(statement_results)
        failed_requests = sum(1 for r in statement_results if not r['is_correct'])
        
        is_faulty = failed_requests > 0
        accuracy = ((total_requests - failed_requests) / total_requests * 100) if total_requests > 0 else 100
        
        # Print detailed error breakdown with policy tracking
        policy_info = f"Policy {policy_index}" if policy_index is not None else f"Policy {policy_name}" if policy_name else "Policy"
        
        if is_faulty:
            must_deny_got_allow = sum(1 for r in statement_results if r['expected_effect'] == 'deny' and r['actual_result'] == 'allow')
            must_allow_got_deny = sum(1 for r in statement_results if r['expected_effect'] == 'allow' and r['actual_result'] == 'deny')
            solver_errors = sum(1 for r in statement_results if r['actual_result'] == 'error')
            
            print(f"{policy_info} - Statement {stmt_id}: {total_requests} requests, {failed_requests} failures, {accuracy:.1f}% accuracy")
            print(f"  Must-deny-got-allow: {must_deny_got_allow}")
            print(f"  Must-allow-got-deny: {must_allow_got_deny}")
            if solver_errors > 0:
                print(f"  Solver errors: {solver_errors}")
        else:
            print(f"{policy_info} - Statement {stmt_id}: {total_requests} requests, {failed_requests} failures, {accuracy:.1f}% accuracy")
        
        return is_faulty, statement_results, accuracy
        
    except Exception as e:
        policy_info = f"Policy {policy_index}" if policy_index is not None else f"Policy {policy_name}" if policy_name else "Policy"
        print(f"{policy_info} - Error testing statement {statement.get('Sid', statement.get('sid', 'Unknown'))}: {e}")
        return True, [], 0  # Consider it faulty if there's an error
        
    finally:
        # Clean up temporary files
        if os.path.exists(temp_policy_file):
            os.unlink(temp_policy_file)
        
        # Clean up SMT files if temp_args was created
        if temp_args is not None:
            smt_file = f"{temp_args.output}_1.smt2"
            if os.path.exists(smt_file):
                os.unlink(smt_file)

def identify_faulty_statements(args):
    """Main function to identify faulty statements and create erroneous policy"""
    reset_solver_calls()

    
    # Determine which policy file to use
    policy_file = None
    if args.policy1:
        policy_file = args.policy1
    elif args.policy2:
        policy_file = args.policy2
    else:
        print("Error: No policy file specified")
        return
    
    # Load requests
    if not args.requests:
        print("Error: No requests given to validate")
        return
    
    # Extract policy name/index from file path for tracking
    policy_name = os.path.basename(policy_file)
    policy_index = None
    
    # Try to extract numeric index from filename (e.g., "5.json" -> 5)
    try:
        base_name = os.path.splitext(policy_name)[0]
        if base_name.isdigit():
            policy_index = int(base_name)
    except:
        pass
    
    # Extract policy structure and statements
    original_policy_structure, statements = extract_policy_statements(policy_file)
    
    policy_info = f"Policy {policy_index}" if policy_index is not None else f"Policy {policy_name}"
    print(f"{policy_info}: Found {len(statements)} statements in policy")
    
    faulty_statements_with_analysis = []
    all_results = []
    statement_analysis = []
    
    print(f"\n{'='*60}")
    print(f"TESTING INDIVIDUAL STATEMENTS - {policy_info}")
    print(f"{'='*60}")
    
    for stmt_idx, statement in enumerate(statements):
        stmt_id = statement.get('Sid', statement.get('sid', f'Statement_{stmt_idx + 1}'))
        print(f"\n{policy_info} - Testing Statement {stmt_idx + 1}/{len(statements)}: {stmt_id}")
        print(f"  Effect: {statement.get('Effect', 'N/A')}")
        print(f"  Action: {statement.get('Action', 'N/A')}")
        print(f"  Resource: {statement.get('Resource', 'N/A')}")
        
        is_faulty, statement_results, accuracy = test_single_statement(statement, original_policy_structure, args, policy_name, policy_index)
        
        # Add statement metadata to results with policy tracking
        for result in statement_results:
            result['policy_name'] = policy_name
            result['policy_index'] = policy_index
            result['policy_file'] = policy_file
            result['statement_index'] = stmt_idx + 1
            result['statement_id'] = stmt_id
            result['statement_effect'] = statement.get('Effect', 'Unknown')
            result['statement_action'] = str(statement.get('Action', 'Unknown'))
            result['statement_resource'] = str(statement.get('Resource', 'Unknown'))
        
        all_results.extend(statement_results)
        
        stmt_analysis = {
            'policy_name': policy_name,
            'policy_index': policy_index,
            'policy_file': policy_file,
            'statement_index': stmt_idx + 1,
            'statement_id': stmt_id,
            'statement': statement,
            'is_faulty': is_faulty,
            'accuracy': accuracy,
            'total_requests': len(statement_results),
            'failed_requests': sum(1 for r in statement_results if not r['is_correct']),
            'results': statement_results 
        }
        
        statement_analysis.append(stmt_analysis)
        
        if is_faulty:
            faulty_statements_with_analysis.append(stmt_analysis)
            print(f"  FAULTY - Added to erroneous policy")
        else:
            print(f"  PASSED - All requests validated correctly")
    
    print(f"\n{policy_info}: Running complete policy validation for fault localization...")
    complete_policy_results = validate_requests(args)
    
    fault_results = perform_fault_localization(complete_policy_results, original_policy_structure, statements, args)
    
    save_fault_localization_results(fault_results, args, policy_name, policy_index)
    
    overall_accuracy = generate_reports(statement_analysis, all_results, args, policy_name, policy_index)
    total_calls = get_solver_calls()
    print(f"\n{policy_info}: Total solver calls: {total_calls}")
    
    return faulty_statements_with_analysis, statement_analysis, overall_accuracy

def validate_requests_for_statement(args, policy_name=None, policy_index=None):
    """Validate requests against a single statement policy"""

    smt_file = f"{args.output}_1.smt2"
    base_smt = []
    with open(smt_file) as f:
        for line in f:
            if line.strip() not in ("(check-sat)", "(get-model)"):
                base_smt.append(line)
    base_smt = ''.join(base_smt)

    # Load requests
    with open(args.requests) as f:
        data = json.load(f)

    statement_results = []
    
    for req in data.get("Requests", []):
        req_id = req.get("id", "unknown")
        
        actions    = req.get("Action")
        resources  = req.get("Resource")
        effect    = req.get("Effect").lower()
        principals = req.get("Principal")
        condition  = req.get("Condition")

        actions   = actions if isinstance(actions, list) else [actions]
        resources = resources if isinstance(resources, list) else [resources]
        principals = principals if isinstance(principals, list) else ([principals] if principals else [None])

        combination_id = 1
        for action in actions:
            for resource in resources:
                for principal in principals:
                    for condition in ([condition] if condition else [None]):
                        
                        # Create individual request ID
                        individual_req_id = f"{req_id}_combo_{combination_id}"
                        combination_id += 1
                        print(f"  {policy_info}: Validating individual request: {individual_req_id}")
                        print(f"    Action: {action}, Resource: {resource}, Principal: {principal}, Condition: {condition}")
                    
                        solver = Solver()
                        smt_parts = [base_smt]

                        # assert action & resource
                        a = (action.lower())
                        r = (resource)
                        smt_parts.append(f'(assert (= action "{a}"))\n')
                        smt_parts.append(f'(assert (= resource "{r}"))\n')

                        # assert principal 
                        if principal:
                            smt_parts.append(f'(assert (= principal "{principal}"))\n')

                        # assert conditions for condition in ([condition] if condition else [None]):
                        # Create individual request ID
                        individual_req_id = f"{req_id}_combo_{combination_id}"
                        combination_id += 1
                    
                        solver = Solver()
                        smt_parts = base_smt

                        a = (action.lower())
                        r = (resource)
                        smt_parts += f'(assert (= action "{a}"))\n'
                        smt_parts += f'(assert (= resource "{r}"))\n'

                        if principal:
                            smt_parts += f'(assert (= principal "{principal}"))\n'

                        if condition:
                            
                            for key, val in condition.items():
                                # k = key.replace(':', '.')
                                # vals = val if isinstance(val, list) else [val]
                                # clauses = []
                                # for v in vals:
                                #     if isinstance(v, int):
                                #         clauses.append(f"(= {k} {v})")
                                #     elif isinstance(v, str) and "Ip" not in key:
                                #         ev = v
                                #         clauses.append(f'(= {k} "{ev}")')
                                #     elif isinstance(v, str):
                                #         addr, pref = bit_string(v)
                                #         re_expr = re2smt(addr[:pref])
                                #         clauses.append(f"(str.in.re {k} {re_expr})")
                                # if clauses:
                                #     if len(clauses) > 1:
                                #         smt_parts.append(f"(assert (or {' '.join(clauses)}))\n")
                                #     else:
                                #         smt_parts.append(f"(assert {clauses[0]})\n")

                                dtype = ops[key]
                            
                                if isinstance(val, dict):
                                    for key2, val2 in val.items():
                                        k = key2.replace(':', '.')
                                        present = ("(declare-const {}".format(k) in smt_parts)
                                        vals = val2 if isinstance(val2, list) else [val2]
                                        to_add = ""
                                        for v in vals:
                                            if dtype == "string":
                                                if not present:
                                                    to_add += "(declare-const {}.exists Bool)\n".format(k)
                                                    to_add += "(declare-const {} String)\n".format(k)
                                                to_add += "(assert {}.exists)\n".format(k)
                                                to_add += "(assert (= {} \"{}\"))\n".format(k,v)
                                            elif dtype == "numeric":
                                                if not present:
                                                    to_add += "(declare-const {}.exists Bool)\n".format(k)
                                                    to_add += "(declare-const {} Int)\n".format(k)
                                                to_add += "(assert {}.exists)\n".format(k)
                                                to_add += "(assert (= {} {}))\n".format(k,v)
                                            elif dtype == "date":
                                                if not present:
                                                    to_add += "(declare-const {}.exists Bool)\n".format(k)
                                                    to_add += "(declare-const {} Int)\n".format(k)
                                                to_add += "(assert {}.exists)\n".format(k)
                                                to_add += "(assert (= {} {}))\n".format(k,unix_time(v))
                                            elif dtype == "ip":
                                                if not present:
                                                    to_add += "(declare-const {}.exists Bool)\n".format(k)
                                                    to_add += "(declare-const {} String)\n".format(k)
                                                to_add += "(assert {}.exists)\n".format(k)
                                                addr,prefix = bit_string(v)
                                                to_add += '(assert (str.in.re {} {}))\n'.format(k, re2smt(addr[:prefix]+".*"))
                                            elif dtype == "bool":
                                                if not present:
                                                    to_add += "(declare-const {}.exists Bool)\n".format(k)
                                                    to_add += "(declare-const {} Bool)\n".format(k)
                                                to_add += "(assert {}.exists)\n".format(k)
                                                to_add += "(assert (= {} {}))\n".format(k,v)
                                                # exit(1)
                                            elif dtype == "null":
                                                print("Error: Cannot have null type in request")
                                                exit(1)
                                            else:
                                                print("Error: Unexpected dtype {}".format(dtype))
                                                exit(1)

                                            smt_parts += to_add

                                        # vals = val2 if isinstance(val2, list) else [val2]
                                        # clauses = []
                                        # for v in vals:
                                        #     if isinstance(v, int):
                                        #         clauses.append(f"(= {k} {v})")
                                        #     elif isinstance(v, str) and "Ip" not in key2:
                                        #         ev = v
                                        #         clauses.append(f'(= {k} "{ev}")')
                                        #     elif isinstance(v, str):
                                        #         addr, pref = bit_string(v)
                                        #         re_expr = re2smt(addr[:pref])
                                        #         clauses.append(f"(str.in.re {k} {re_expr})")
                                        # if clauses:
                                        #     if len(clauses) > 1:
                                        #         smt_parts.append(f"(assert (or {' '.join(clauses)}))\n")
                                        #     else:
                                        #         smt_parts.append(f"(assert {clauses[0]})\n")

                        print(smt_parts)
                        smt_parts += "(check-sat)"
                        full_smt = smt_parts.replace('\x00', '\x01')
                
                        # Solve - EXACTLY LIKE CORE FUNCTIONALITY
                        try:
                            solver.from_string(full_smt)
                            
                            increment_solver_calls() 
                            start_time = time.time()
                            solver_result = solver.check()
                            elapsed_time = time.time() - start_time
                            # Determine actual result
                            actual_result = 'allow' if solver_result == sat else 'deny'
                            
                            # Check if the result matches expectation
                            is_correct = ((solver_result == sat and effect == 'allow') or 
                                        (solver_result != sat and effect == 'deny'))
                            
                            # Store individual result with policy tracking
                            individual_result = {
                                'policy_name': policy_name,
                                'policy_index': policy_index,
                                'request_object_id': req_id,
                                'individual_request_id': individual_req_id,
                                'action': action,
                                'resource': resource,
                                'principal': principal if principal else 'None',
                                'condition': str(condition) if condition else 'None',
                                'expected_effect': effect,
                                'actual_result': actual_result,
                                'solver_result': str(solver_result),
                                'is_correct': is_correct,
                                'solver_call_time': elapsed_time,
                                'solver_call_count': get_solver_calls()
                            }
                            
                            statement_results.append(individual_result)

                        except Exception as e:
                            print(f"      Exception during solving: {e}")
                            individual_result = {
                                'policy_name': policy_name,
                                'policy_index': policy_index,
                                'request_object_id': req_id,
                                'individual_request_id': individual_req_id,
                                'action': action,
                                'resource': resource,
                                'principal': principal if principal else 'None',
                                'condition': str(condition) if condition else 'None',
                                'expected_effect': effect,
                                'actual_result': 'error',
                                'solver_result': 'error',
                                'is_correct': False,
                                'solver_call_time': 0,
                                'solver_call_count': 0
                            }
                            statement_results.append(individual_result)

    return statement_results

def generate_reports(statement_analysis, all_results, args, policy_name=None, policy_index=None):
    """Generate comprehensive reports"""
    
    policy_info = f"Policy {policy_index}" if policy_index is not None else f"Policy {policy_name}" if policy_name else "Policy"
    
    home_dir = Path(args.output_dir)
    home_dir.mkdir(parents=True, exist_ok=True)

    if args.output and os.path.isabs(args.output):
        base_filename = os.path.basename(args.output)
    else:
        base_filename = args.output if args.output else "policy_validation"

    # Console summary
    total_statements = len(statement_analysis)
    faulty_statements = [s for s in statement_analysis if s['is_faulty']]
    working_statements = [s for s in statement_analysis if not s['is_faulty']]
    
    # Calculate overall accuracy from all individual results
    total_individual_requests = len(all_results)
    correct_requests = sum(1 for r in all_results if r['is_correct'])
    overall_accuracy = (correct_requests / total_individual_requests * 100) if total_individual_requests > 0 else 0
    
    print(f"\n{'='*80}")
    print(f"FINAL SUMMARY - {policy_info}")
    print(f"{'='*80}")
    print(f"Policy File: {args.policy1 if args.policy1 else args.policy2}")
    print(f"Policy Name: {policy_name}")
    if policy_index is not None:
        print(f"Policy Index: {policy_index}")
    print(f"Total Statements Analyzed: {total_statements}")
    print(f"Faulty Statements: {len(faulty_statements)}")
    print(f"Working Statements: {len(working_statements)}")
    print(f"Overall Policy Health: {(len(working_statements)/total_statements*100):.1f}%")
    print(f"")
    print(f"INDIVIDUAL REQUEST ANALYSIS:")
    print(f"Total Individual Requests: {total_individual_requests}")
    print(f"Correct Classifications: {correct_requests}")
    print(f"Incorrect Classifications: {total_individual_requests - correct_requests}")
    print(f"Overall Accuracy: {overall_accuracy:.1f}%")
    
    if faulty_statements:
        print(f"\n Faulty Statements Detail:")
        for stmt in faulty_statements:
            print(f"  {stmt['statement_id']}: {stmt['failed_requests']}/{stmt['total_requests']} failed ({stmt['accuracy']:.1f}% accuracy)")
    
    # Save detailed CSV with policy tracking
    detailed_csv_path = home_dir / f"{base_filename}_statement_analysis.csv"
    with open(detailed_csv_path, 'w', newline='', encoding='utf-8') as csvfile:
        fieldnames = ['policy_name', 'policy_index', 'policy_file', 'statement_index', 'statement_id', 
                     'statement_effect', 'statement_action', 'statement_resource', 'request_object_id', 
                     'individual_request_id', 'action', 'resource', 'principal', 'condition', 
                     'expected_effect', 'actual_result', 'solver_result', 'is_correct', 
                     'solver_call_time', 'solver_call_count']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        
        writer.writeheader()
        for result in all_results:
            writer.writerow(result)
    
    # Save statement summary with policy tracking
    summary_csv_path = home_dir / f"{base_filename}_statement_summary.csv"
    with open(summary_csv_path, 'w', newline='', encoding='utf-8') as csvfile:
        fieldnames = ['policy_name', 'policy_index', 'policy_file', 'statement_index', 'statement_id', 
                     'is_faulty', 'accuracy', 'total_requests', 'failed_requests', 'statement_effect', 
                     'statement_action', 'statement_resource']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        
        writer.writeheader()
        for stmt in statement_analysis:
            writer.writerow({
                'policy_name': stmt['policy_name'],
                'policy_index': stmt['policy_index'],
                'policy_file': stmt['policy_file'],
                'statement_index': stmt['statement_index'],
                'statement_id': stmt['statement_id'],
                'is_faulty': stmt['is_faulty'],
                'accuracy': f"{stmt['accuracy']:.1f}",
                'total_requests': stmt['total_requests'],
                'failed_requests': stmt['failed_requests'],
                'statement_effect': stmt['statement'].get('Effect', 'Unknown'),
                'statement_action': str(stmt['statement'].get('Action', 'Unknown')),
                'statement_resource': str(stmt['statement'].get('Resource', 'Unknown'))
            })
    
    # Save overall summary with accuracy and policy tracking
    overall_summary_csv_path = home_dir / f"{base_filename}_overall_summary.csv"
    with open(overall_summary_csv_path, 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['Metric', 'Value'])
        writer.writerow(['Policy Name', policy_name])
        writer.writerow(['Policy Index', policy_index])
        writer.writerow(['Policy File', args.policy1 if args.policy1 else args.policy2])
        writer.writerow(['Requests File', args.requests])
        writer.writerow(['', ''])
        writer.writerow(['Total Statements Analyzed', total_statements])
        writer.writerow(['Faulty Statements', len(faulty_statements)])
        writer.writerow(['Working Statements', len(working_statements)])
        writer.writerow(['Statement-level Policy Health (%)', f"{(len(working_statements)/total_statements*100):.1f}"])
        writer.writerow(['', ''])
        writer.writerow(['Total Individual Requests', total_individual_requests])
        writer.writerow(['Correct Classifications', correct_requests])
        writer.writerow(['Incorrect Classifications', total_individual_requests - correct_requests])
        writer.writerow(['Overall Accuracy (%)', f"{overall_accuracy:.1f}"])
    
    print(f"\n{policy_info}: Reports saved to:")
    print(f"  Detailed analysis: {detailed_csv_path}")
    print(f"  Statement summary: {summary_csv_path}")
    print(f"  Overall summary: {overall_summary_csv_path}")
    
    return overall_accuracy

#this logic should be untouched. this is how the validation works. 
def validate_requests(args):
    """Original validate_requests function """
    reset_solver_calls()
    
    # Extract policy name/index from file path for tracking
    policy_file = args.policy1 if args.policy1 else args.policy2
    policy_name = os.path.basename(policy_file) if policy_file else "unknown"
    policy_index = None
    
    # Try to extract numeric index from filename (e.g., "5.json" -> 5)
    try:
        base_name = os.path.splitext(policy_name)[0]
        if base_name.isdigit():
            policy_index = int(base_name)
    except:
        pass
    
    policy_info = f"Policy {policy_index}" if policy_index is not None else f"Policy {policy_name}"
    
    # 1) Translate policy into SMT constraints
    call_translator(args)
    smt_file = f"{args.output}_1.smt2"
    base_smt = []
    with open(smt_file) as f:
        for line in f:
            if line.strip() not in ("(check-sat)", "(get-model)"):
                base_smt.append(line)
    base_smt = ''.join(base_smt)

    # 2) Load requests
    if not args.requests:
        print("Error: No requests given to validate")
        return
    with open(args.requests) as f:
        data = json.load(f)

    all_individual_results = []
    
    for req in data.get("Requests", []):
        req_id = req.get("id", "unknown")
        print(f"{policy_info}: Processing request object: {req_id}")
        
        actions    = req.get("Action")
        resources  = req.get("Resource")
        effect    = req.get("Effect").lower()
        principals = req.get("Principal")
        condition  = req.get("Condition")


        actions   = actions if isinstance(actions, list) else [actions]
        resources = resources if isinstance(resources, list) else [resources]
        principals = principals if isinstance(principals, list) else ([principals] if principals else [None])

        # Generate all combinations for this request object 
        combination_id = 1
        for action in actions:
            for resource in resources:
                for principal in principals:
                    for condition in ([condition] if condition else [None]):
                        
                        # Create individual request ID
                        individual_req_id = f"{req_id}_combo_{combination_id}"
                        combination_id += 1
                        print(f"  {policy_info}: Validating individual request: {individual_req_id}")
                        print(f"    Action: {action}, Resource: {resource}, Principal: {principal}, Condition: {condition}")
                    
                        solver = Solver()
                        smt_parts = [base_smt]

                        # assert action & resource
                        a = (action.lower())
                        r = (resource)
                        smt_parts.append(f'(assert (= action "{a}"))\n')
                        smt_parts.append(f'(assert (= resource "{r}"))\n')

                        # assert principal 
                        if principal:
                            smt_parts.append(f'(assert (= principal "{principal}"))\n')

                        # assert conditions for condition in ([condition] if condition else [None]):
                        # Create individual request ID
                        individual_req_id = f"{req_id}_combo_{combination_id}"
                        combination_id += 1
                    
                        solver = Solver()
                        smt_parts = base_smt

                        # assert action & resource - EXACTLY LIKE CORE FUNCTIONALITY
                        a = (action.lower())
                        r = (resource)
                        smt_parts += f'(assert (= action "{a}"))\n'
                        smt_parts += f'(assert (= resource "{r}"))\n'

                        if principal:
                            smt_parts += f'(assert (= principal "{principal}"))\n'

                        # assert conditions - EXACTLY LIKE CORE FUNCTIONALITY
                        if condition:
                            
                            for key, val in condition.items():
                                # k = key.replace(':', '.')
                                # vals = val if isinstance(val, list) else [val]
                                # clauses = []
                                # for v in vals:
                                #     if isinstance(v, int):
                                #         clauses.append(f"(= {k} {v})")
                                #     elif isinstance(v, str) and "Ip" not in key:
                                #         ev = v
                                #         clauses.append(f'(= {k} "{ev}")')
                                #     elif isinstance(v, str):
                                #         addr, pref = bit_string(v)
                                #         re_expr = re2smt(addr[:pref])
                                #         clauses.append(f"(str.in.re {k} {re_expr})")
                                # if clauses:
                                #     if len(clauses) > 1:
                                #         smt_parts.append(f"(assert (or {' '.join(clauses)}))\n")
                                #     else:
                                #         smt_parts.append(f"(assert {clauses[0]})\n")

                                dtype = ops[key]
                            
                                if isinstance(val, dict):
                                    for key2, val2 in val.items():
                                        k = key2.replace(':', '.')
                                        present = ("(declare-const {}".format(k) in smt_parts)
                                        vals = val2 if isinstance(val2, list) else [val2]
                                        to_add = ""
                                        for v in vals:
                                            if dtype == "string":
                                                if not present:
                                                    to_add += "(declare-const {}.exists Bool)\n".format(k)
                                                    to_add += "(declare-const {} String)\n".format(k)
                                                to_add += "(assert {}.exists)\n".format(k)
                                                to_add += "(assert (= {} \"{}\"))\n".format(k,v)
                                            elif dtype == "numeric":
                                                if not present:
                                                    to_add += "(declare-const {}.exists Bool)\n".format(k)
                                                    to_add += "(declare-const {} Int)\n".format(k)
                                                to_add += "(assert {}.exists)\n".format(k)
                                                to_add += "(assert (= {} {}))\n".format(k,v)
                                            elif dtype == "date":
                                                if not present:
                                                    to_add += "(declare-const {}.exists Bool)\n".format(k)
                                                    to_add += "(declare-const {} Int)\n".format(k)
                                                to_add += "(assert {}.exists)\n".format(k)
                                                to_add += "(assert (= {} {}))\n".format(k,unix_time(v))
                                            elif dtype == "ip":
                                                if not present:
                                                    to_add += "(declare-const {}.exists Bool)\n".format(k)
                                                    to_add += "(declare-const {} String)\n".format(k)
                                                to_add += "(assert {}.exists)\n".format(k)
                                                addr,prefix = bit_string(v)
                                                to_add += '(assert (str.in.re {} {}))\n'.format(k, re2smt(addr[:prefix]+".*"))
                                            elif dtype == "bool":
                                                if not present:
                                                    to_add += "(declare-const {}.exists Bool)\n".format(k)
                                                    to_add += "(declare-const {} Bool)\n".format(k)
                                                to_add += "(assert {}.exists)\n".format(k)
                                                to_add += "(assert (= {} {}))\n".format(k,v)
                                                # exit(1)
                                            elif dtype == "null":
                                                print("Error: Cannot have null type in request")
                                                exit(1)
                                            else:
                                                print("Error: Unexpected dtype {}".format(dtype))
                                                exit(1)

                                            smt_parts += to_add

                                        # vals = val2 if isinstance(val2, list) else [val2]
                                        # clauses = []
                                        # for v in vals:
                                        #     if isinstance(v, int):
                                        #         clauses.append(f"(= {k} {v})")
                                        #     elif isinstance(v, str) and "Ip" not in key2:
                                        #         ev = v
                                        #         clauses.append(f'(= {k} "{ev}")')
                                        #     elif isinstance(v, str):
                                        #         addr, pref = bit_string(v)
                                        #         re_expr = re2smt(addr[:pref])
                                        #         clauses.append(f"(str.in.re {k} {re_expr})")
                                        # if clauses:
                                        #     if len(clauses) > 1:
                                        #         smt_parts.append(f"(assert (or {' '.join(clauses)}))\n")
                                        #     else:
                                        #         smt_parts.append(f"(assert {clauses[0]})\n")

                        print(smt_parts)
                        smt_parts += "(check-sat)"
                        full_smt = smt_parts.replace('\x00', '\x01')
                
                        elapsed_time = 0
                        try:
                            solver.from_string(full_smt)
                            increment_solver_calls() 

                            initial_time = time.time()
                            solver_result = solver.check()
                            end_time = time.time()
                            elapsed_time = end_time - initial_time
                            print(f"Solver time: {elapsed_time:.4f} seconds")
                            print(f"Solver result: {solver_result}")                    
                            
                            actual_result = 'allow' if solver_result == sat else 'deny'

                            is_correct = ((solver_result == sat and effect == 'allow') or
                                          (solver_result != sat and effect == 'deny'))

                            # Store individual result with policy tracking
                            individual_result = {
                                'policy_name': policy_name,
                                'policy_index': policy_index,
                                'policy_file': policy_file,
                                'request_object_id': req_id,
                                'individual_request_id': individual_req_id,
                                'action': action,
                                'resource': resource,
                                'principal': principal if principal else 'None',
                                'condition': str(condition) if condition else 'None',
                                'expected_effect': effect,
                                'actual_result': actual_result,
                                'solver_result': str(solver_result),
                                'is_correct': is_correct,
                                'solver_call_time': elapsed_time,
                                'solver_call_count': get_solver_calls()
                            }
                            
                            all_individual_results.append(individual_result)
                            
                            status = "CORRECT" if is_correct else "INCORRECT"
                            print(f"    {status}: Expected={effect}, Got={actual_result}")

                            print()
                        except Exception as e:
                            print(f"    Exception during solving: {e}")
                            individual_result = {
                                'policy_name': policy_name,
                                'policy_index': policy_index,
                                'policy_file': policy_file,
                                'request_object_id': req_id,
                                'individual_request_id': individual_req_id,
                                'action': action,
                                'resource': resource,
                                'principal': principal if principal else 'None',
                                'condition': str(condition) if condition else 'None',
                                'expected_effect': effect,
                                'actual_result': 'error',
                                'solver_result': 'error',
                                'is_correct': False,
                                'solver_call_time': elapsed_time,
                                'solver_call_count': get_solver_calls()
                            }
                            all_individual_results.append(individual_result)
    
    # Calculate and report overall accuracy
    total_individual_requests = len(all_individual_results)
    correct_count = sum(1 for r in all_individual_results if r['is_correct'])
    incorrect_count = total_individual_requests - correct_count
    errors = sum(1 for r in all_individual_results if r['actual_result'] == 'error')
    overall_accuracy = (correct_count / total_individual_requests * 100) if total_individual_requests > 0 else 0

    # Count by expected vs actual
    correct_allow = sum(1 for r in all_individual_results if r['expected_effect'] == 'allow' and r['actual_result'] == 'allow')
    correct_deny = sum(1 for r in all_individual_results if r['expected_effect'] == 'deny' and r['actual_result'] == 'deny')
    misclassified_allow_to_deny = sum(1 for r in all_individual_results if r['expected_effect'] == 'allow' and r['actual_result'] == 'deny')
    misclassified_deny_to_allow = sum(1 for r in all_individual_results if r['expected_effect'] == 'deny' and r['actual_result'] == 'allow')
    total_calls = get_solver_calls()

    print("\n" + "="*60)
    print(f"INDIVIDUAL REQUEST ANALYSIS - {policy_info}")
    print("="*60)
    print(f"Policy File: {policy_file}")
    print(f"Policy Name: {policy_name}")
    if policy_index is not None:
        print(f"Policy Index: {policy_index}")
    print(f"Total Individual Requests: {total_individual_requests}")
    print(f"Correct Classifications: {correct_count}")
    print(f"Incorrect Classifications: {incorrect_count}")
    print(f"Errors: {errors}")
    print(f"Overall Accuracy: {overall_accuracy:.1f}%")
    print()
    print("Expected vs Actual:")
    print(f"  Expected Allow -> Got Allow: {correct_allow}")
    print(f"  Expected Allow -> Got Deny: {misclassified_allow_to_deny}")
    print(f"  Expected Deny -> Got Deny: {correct_deny}")
    print(f"  Expected Deny -> Got Allow: {misclassified_deny_to_allow}")
    print("="*60)
    print(f"Total Solver Calls: {total_calls}")


    return all_individual_results

if __name__ == '__main__':
    parser = ap.ArgumentParser(description = 'Validate requests against AWS policy using SMT formulas')
    parser.add_argument('-p1' , '--policy1'         , help = 'policy 1 (AWS)'               , required = False)
    parser.add_argument('-p2' , '--policy2'         , help = 'policy 2 (AWS)'               , required = False)
    parser.add_argument('-rd' , '--role-definitions', help = 'role definitions (Azure)'     , required = False)
    parser.add_argument('-ra1', '--role-assignment1', help = 'role assignment 1 (Azure)'    , required = False)
    parser.add_argument('-ra2', '--role-assignment2', help = 'role assignment 2 (Azure)'    , required = False)
    parser.add_argument('-r'  , '--roles'           , help = 'roles (GCP)'                  , required = False)
    parser.add_argument('-rb1', '--role-binding1'   , help = 'role binding 1 (GCP)'         , required = False)
    parser.add_argument('-rb2', '--role-binding2'   , help = 'role binding 2 (GCP)'         , required = False)
    parser.add_argument('-o'  , '--output'          , help = 'output file'                  , required = False, default='output')
    parser.add_argument('-s'  , '--smt-lib'         , help = 'use SMT-LIB syntax'           , required = False, action = 'store_true')
    parser.add_argument('-e'  , '--enc'             , help = 'use action encoding'          , required = False, action = 'store_true')
    parser.add_argument('-c'  , '--constraints'     , help = 'use resource type constraints', required = False, action = 'store_true')
    parser.add_argument('-rq' , '--requests'        , help = 'check if requests in a json-formatted list are accepted by the policy', required = False)
    parser.add_argument('--identify-faulty', help = 'identify faulty statements and create erroneous policy', action = 'store_true')
    parser.add_argument('-rn', '--req-num',   help = 'request set identifier used to locate output directories', required = False)
    parser.add_argument('-od', '--output-dir', help = 'directory to save output reports',                         required = False, default = '.')

    args = parser.parse_args()
    req_num = args.req_num

    if args.identify_faulty:
        identify_faulty_statements(args)
    else:
        call_translator(args)
        validate_requests(args)